language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - pytest --cov-report=xml --cov=pygosolnp tests/

after_success:
  - codecov

deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: YtTqVZC2iqDQEhtNGXpaEWtLXff0MJhMm1+5XkGb0uPCpZVk5E1TKy3E45DMLreCbVaWkcxbDY9gx+gy/hJvJLwSgGM3JeqYwMA1czBePsvi/Lnj9WV/jkQLE20IjIrnEFArfD6XU+oXqvebWTvxmPTNj7nZ0h1oNiom0eu7aCfY1wQRuxX+Fob2DhBKt8A4CbFwrXaiW0cvAs5Lx+JVpx+NyUUpKhOJmapP2hKH832OENeB3LHwFguER/jsz9vg/6AoGZCxBICi/CPAG/v+EERPOySERo/sKP8AZkWhby2ryfq6Blhmkmg+jHIqSQ1OqRkotY4xdznHxmt1BokNmyharEjfhBdWu+TRgvt7EE+RGgaEMRupbg45dGzfvBHrvyfJPkb/KMXMFJ8kLt6yaVSsEXBAhs+DxIY/8giX5WjAZyuIJlxKSKFq72P0rx1v2ERjwehNgeALqKLGXbXKIuBTLD74sFdFHXHSIWCDyJo8tyET/MUPefyZcPu341WA9JbOe4xI/yQRRprcZRv7N/897j2C+68CMmUdRJTC1lx7LVHe2bGl9VmUt/wyS1LutWi4RrkYEl3DRWIH+JJn3dZltAOuG/d1jbdGpFrXKDX+ybSNcB7Zh7wkBHc4ulxz+8E/y8zJDyZjm3Exwa5UI2LxsdIMZOBfCTG1liwSSGk=
    server: https://test.pypi.org/legacy/
    skip_existing: true
    skip_cleanup: true
    on:
       branch: main
  - provider: pypi
    user: "__token__"
    password:
      secure:  CGaJ9sSE2JVPggcZKu4IAZeRs7AMD1NiJ17XhOLCiXZZWp9ereaUnNdcz2sOQnqEteZiPyxM8UVXOIixjY/8Amv40tO9T/N6ZcpDG2cC/KDcc91vkzEA4mmxqejfX1S0I1SQXzRM6sCtuTCSL/MirduXLWDM4pZz0pWlKfQ4juWIqdhKU09I0cPn2ibXRfVxOBLf1rxVOKnDv7Y7C03NYmnn1Sv/xhYAiKxCl76oAlOwjzZKyBd59bL9SUUvqSc+dBRLZ//WExwCAbQjtOtWxQsO+LClxmireLTcGIZ4Hq1L3mKkTphR3REWd3Y5UfDXUsp7OV4Mh74dTjFPDrseaSWGmg4DtUb/iiL1DKYeGYKol7Z3m1uwRl1TjifDm2pFr3SCQ2ELl4JP7e9Js8w2mN8qBlaW4O3S+LxkzreDkQFz4mICnctHGEixasA/5HBDzuIydrPm8guBj7qCoMDMBlPeXLd/GM/8zYHQESnyhhG+IZs6p3wbVd+UNz2eRfEhT57pFAZUc4bB7mBiEtyNqxlRMkPet6T+rJcHr54CnHWS6tiZfL0ehq6CMILPi5+gJR+tdHJAxrRVbfATjbvWdty5qOz7S6gnHilm4E5U1QMWGC2GR997UoOeEqxcScDK0+5po6DulJhkV7qCdtON1lwHp8StAXhX8BJCYsHu94Y=
    skip_existing: true
    skip_cleanup: true
    on:
      branch: release