language: python

python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - pytest --cov-report=xml --cov=pygosolnp tests/

after_success:
  - codecov

deploy:
  - provider: pypi
    user: "__token__"
    password: $TEST_PYPI_TOKEN
    server: https://test.pypi.org/legacy/
    distributions: "sdist bdist_wheel"
    skip_existing: true
    skip_cleanup: true
    on:
       branch: main
  - provider: pypi
    user: "__token__"
    password: $PYPI_TOKEN
    distributions: "sdist bdist_wheel"
    skip_existing: true
    skip_cleanup: true
    on:
      branch: release